services:
  flask-app:
    build:
      context: ./flask_app
      dockerfile: Dockerfile
    container_name: bball_flask_app
    ports:
      - "4000:5000"
    volumes:
      - ./flask_app:/app
      - ${RAW_DATA_DIR}:/app/src/data/raw_data
    environment:
      - DB_PATH=/app/data/bball.db
      - DATA_DIR=/app/data
      - DATA_241_API_KEY=${DATA_241_API_KEY}
    networks:
      - bball-network

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    container_name: bball_swagger_ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON_URL=http://localhost:4000/docs/openapi.json
    depends_on:
      - flask-app
    networks:
      - bball-network

networks:
  bball-network:
    driver: bridge
